export type Sector =
  | 'Technology'
  | 'Finance'
  | 'Crypto'
  | 'Energy'
  | 'Healthcare'
  | 'Consumer'
  | 'EV'
  | 'Automotive'
  | 'Industrial'
  | 'ETF'
  | 'Materials'
  | 'Real Estate'
  | 'Utilities'
  | 'Telecom';

export interface StockMeta {
  ticker: string;
  name: string;
  sector: Sector;
}

export const STOCK_LIST: StockMeta[] = [
  // ── High IV momentum / meme stocks ───────────────────────────────────────
  { ticker: 'GME',   name: 'GameStop',                  sector: 'Consumer'    },
  { ticker: 'MARA',  name: 'Marathon Digital',           sector: 'Crypto'      },
  { ticker: 'SOFI',  name: 'SoFi Technologies',          sector: 'Finance'     },
  { ticker: 'RIVN',  name: 'Rivian Automotive',          sector: 'EV'          },
  { ticker: 'COIN',  name: 'Coinbase',                   sector: 'Crypto'      },
  { ticker: 'HOOD',  name: 'Robinhood',                  sector: 'Finance'     },
  { ticker: 'AMC',   name: 'AMC Entertainment',          sector: 'Consumer'    },
  { ticker: 'PLTR',  name: 'Palantir',                   sector: 'Technology'  },
  { ticker: 'RBLX',  name: 'Roblox',                     sector: 'Technology'  },
  { ticker: 'SNAP',  name: 'Snap',                       sector: 'Technology'  },
  { ticker: 'UBER',  name: 'Uber',                       sector: 'Technology'  },
  { ticker: 'LYFT',  name: 'Lyft',                       sector: 'Technology'  },
  { ticker: 'IONQ',  name: 'IonQ',                       sector: 'Technology'  },
  { ticker: 'SMCI',  name: 'Super Micro Computer',       sector: 'Technology'  },
  { ticker: 'NVAX',  name: 'Novavax',                    sector: 'Healthcare'  },
  { ticker: 'TLRY',  name: 'Tilray Brands',              sector: 'Consumer'    },
  { ticker: 'RIOT',  name: 'Riot Platforms',             sector: 'Crypto'      },
  { ticker: 'CLSK',  name: 'CleanSpark',                 sector: 'Crypto'      },
  { ticker: 'MSTR',  name: 'MicroStrategy',              sector: 'Crypto'      },
  { ticker: 'WULF',  name: 'TeraWulf',                   sector: 'Crypto'      },

  // ── Popular growth tech ───────────────────────────────────────────────────
  { ticker: 'TSLA',  name: 'Tesla',                      sector: 'EV'          },
  { ticker: 'NVDA',  name: 'NVIDIA',                     sector: 'Technology'  },
  { ticker: 'AMD',   name: 'Advanced Micro Devices',     sector: 'Technology'  },
  { ticker: 'META',  name: 'Meta Platforms',             sector: 'Technology'  },
  { ticker: 'NFLX',  name: 'Netflix',                    sector: 'Technology'  },
  { ticker: 'SHOP',  name: 'Shopify',                    sector: 'Technology'  },
  { ticker: 'XYZ',   name: 'Block',                      sector: 'Finance'     },
  { ticker: 'ROKU',  name: 'Roku',                       sector: 'Technology'  },
  { ticker: 'NET',   name: 'Cloudflare',                 sector: 'Technology'  },
  { ticker: 'DDOG',  name: 'Datadog',                    sector: 'Technology'  },
  { ticker: 'CRWD',  name: 'CrowdStrike',                sector: 'Technology'  },
  { ticker: 'SNOW',  name: 'Snowflake',                  sector: 'Technology'  },
  { ticker: 'ZM',    name: 'Zoom',                       sector: 'Technology'  },
  { ticker: 'DOCN',  name: 'DigitalOcean',               sector: 'Technology'  },
  { ticker: 'MDB',   name: 'MongoDB',                    sector: 'Technology'  },
  { ticker: 'BILL',  name: 'Bill Holdings',              sector: 'Finance'     },
  { ticker: 'AFRM',  name: 'Affirm',                     sector: 'Finance'     },
  { ticker: 'UPST',  name: 'Upstart',                    sector: 'Finance'     },
  { ticker: 'OPEN',  name: 'Opendoor',                   sector: 'Finance'     },
  { ticker: 'ABNB',  name: 'Airbnb',                     sector: 'Consumer'    },

  // ── Large cap blue chip ───────────────────────────────────────────────────
  { ticker: 'AAPL',  name: 'Apple',                      sector: 'Technology'  },
  { ticker: 'MSFT',  name: 'Microsoft',                  sector: 'Technology'  },
  { ticker: 'GOOGL', name: 'Alphabet Class A',           sector: 'Technology'  },
  { ticker: 'AMZN',  name: 'Amazon',                     sector: 'Technology'  },
  { ticker: 'JPM',   name: 'JPMorgan Chase',             sector: 'Finance'     },
  { ticker: 'BAC',   name: 'Bank of America',            sector: 'Finance'     },
  { ticker: 'GS',    name: 'Goldman Sachs',              sector: 'Finance'     },
  { ticker: 'XOM',   name: 'ExxonMobil',                 sector: 'Energy'      },
  { ticker: 'CVX',   name: 'Chevron',                    sector: 'Energy'      },
  { ticker: 'DIS',   name: 'Walt Disney',                sector: 'Consumer'    },
  { ticker: 'NKE',   name: 'Nike',                       sector: 'Consumer'    },
  { ticker: 'BA',    name: 'Boeing',                     sector: 'Industrial'  },
  { ticker: 'F',     name: 'Ford Motor',                 sector: 'Automotive'  },
  { ticker: 'GM',    name: 'General Motors',             sector: 'Automotive'  },
  { ticker: 'PFE',   name: 'Pfizer',                     sector: 'Healthcare'  },

  // ── Core ETFs ─────────────────────────────────────────────────────────────
  { ticker: 'SPY',   name: 'S&P 500 ETF',                sector: 'ETF'         },
  { ticker: 'QQQ',   name: 'Nasdaq 100 ETF',             sector: 'ETF'         },
  { ticker: 'IWM',   name: 'Russell 2000 ETF',           sector: 'ETF'         },
  { ticker: 'GLD',   name: 'Gold ETF',                   sector: 'ETF'         },
  { ticker: 'SLV',   name: 'Silver ETF',                 sector: 'ETF'         },
  { ticker: 'TLT',   name: '20yr Treasury ETF',          sector: 'ETF'         },
  { ticker: 'XLE',   name: 'Energy Select ETF',          sector: 'ETF'         },
  { ticker: 'XLF',   name: 'Financial Select ETF',       sector: 'ETF'         },
  { ticker: 'ARKK',  name: 'ARK Innovation ETF',         sector: 'ETF'         },
  { ticker: 'SOXL',  name: 'Semiconductor Bull 3x ETF',  sector: 'ETF'         },

  // ── Speculative / AI / quantum ────────────────────────────────────────────
  { ticker: 'LCID',  name: 'Lucid Group',                sector: 'EV'          },
  { ticker: 'ACHR',  name: 'Archer Aviation',              sector: 'EV'          },
  { ticker: 'CLOV',  name: 'Clover Health',              sector: 'Healthcare'  },
  { ticker: 'BBAI',  name: 'BigBear.ai',                 sector: 'Technology'  },
  { ticker: 'SOUN',  name: 'SoundHound AI',              sector: 'Technology'  },
  { ticker: 'AISP',  name: 'Airship AI',                 sector: 'Technology'  },
  { ticker: 'RGTI',  name: 'Rigetti Computing',          sector: 'Technology'  },
  { ticker: 'QBTS',  name: 'D-Wave Quantum',             sector: 'Technology'  },
  { ticker: 'KULR',  name: 'KULR Technology',            sector: 'Technology'  },
  { ticker: 'HIMS',  name: 'Hims & Hers Health',         sector: 'Healthcare'  },

  // ── Additional ETFs ───────────────────────────────────────────────────────
  { ticker: 'TQQQ',  name: 'Nasdaq 100 Bull 3x ETF',     sector: 'ETF'         },
  { ticker: 'SQQQ',  name: 'Nasdaq 100 Bear 3x ETF',     sector: 'ETF'         },
  { ticker: 'SPXL',  name: 'S&P 500 Bull 3x ETF',        sector: 'ETF'         },
  { ticker: 'SPXS',  name: 'S&P 500 Bear 3x ETF',        sector: 'ETF'         },
  { ticker: 'UVXY',  name: 'VIX Short-Term Bull ETF',    sector: 'ETF'         },
  { ticker: 'VXX',   name: 'VIX Short-Term Futures ETF', sector: 'ETF'         },
  { ticker: 'SMH',   name: 'Semiconductor ETF',          sector: 'ETF'         },
  { ticker: 'SOXX',  name: 'Semiconductor ETF (iShares)',sector: 'ETF'         },
  { ticker: 'XLK',   name: 'Technology Select ETF',      sector: 'ETF'         },
  { ticker: 'XLV',   name: 'Health Care Select ETF',     sector: 'ETF'         },
  { ticker: 'XLI',   name: 'Industrial Select ETF',      sector: 'ETF'         },
  { ticker: 'XLB',   name: 'Materials Select ETF',       sector: 'ETF'         },
  { ticker: 'XLU',   name: 'Utilities Select ETF',       sector: 'ETF'         },
  { ticker: 'XLRE',  name: 'Real Estate Select ETF',     sector: 'ETF'         },
  { ticker: 'XLC',   name: 'Communication Services ETF', sector: 'ETF'         },
  { ticker: 'XLY',   name: 'Consumer Discretionary ETF', sector: 'ETF'         },
  { ticker: 'XLP',   name: 'Consumer Staples ETF',       sector: 'ETF'         },
  { ticker: 'GDX',   name: 'Gold Miners ETF',            sector: 'ETF'         },
  { ticker: 'GDXJ',  name: 'Junior Gold Miners ETF',     sector: 'ETF'         },
  { ticker: 'USO',   name: 'Oil Fund ETF',               sector: 'ETF'         },
  { ticker: 'XOP',   name: 'Oil & Gas E&P ETF',          sector: 'ETF'         },
  { ticker: 'IBIT',  name: 'Bitcoin ETF (BlackRock)',     sector: 'ETF'         },
  { ticker: 'EEM',   name: 'Emerging Markets ETF',       sector: 'ETF'         },
  { ticker: 'EFA',   name: 'Developed Markets ETF',      sector: 'ETF'         },
  { ticker: 'VTI',   name: 'Total Stock Market ETF',     sector: 'ETF'         },
  { ticker: 'VOO',   name: 'Vanguard S&P 500 ETF',       sector: 'ETF'         },
  { ticker: 'KWEB',  name: 'China Internet ETF',         sector: 'ETF'         },
  { ticker: 'FXI',   name: 'China Large-Cap ETF',        sector: 'ETF'         },
  { ticker: 'BITO',  name: 'Bitcoin Strategy ETF',       sector: 'ETF'         },
  { ticker: 'JETS',  name: 'Airlines ETF',               sector: 'ETF'         },
  { ticker: 'ARKW',  name: 'ARK Next Gen Internet ETF',  sector: 'ETF'         },
  { ticker: 'ARKG',  name: 'ARK Genomics ETF',           sector: 'ETF'         },
  { ticker: 'BOIL',  name: 'Natural Gas Bull 2x ETF',    sector: 'ETF'         },
  { ticker: 'LABU',  name: 'Biotech Bull 3x ETF',        sector: 'ETF'         },
  { ticker: 'LABD',  name: 'Biotech Bear 3x ETF',        sector: 'ETF'         },
  { ticker: 'FNGU',  name: 'FANG+ Bull 3x ETN',          sector: 'ETF'         },
  { ticker: 'FNGD',  name: 'FANG+ Bear 3x ETN',          sector: 'ETF'         },
  { ticker: 'HYG',   name: 'High Yield Bond ETF',        sector: 'ETF'         },
  { ticker: 'LQD',   name: 'Investment Grade Bond ETF',  sector: 'ETF'         },
  { ticker: 'IAU',   name: 'Gold ETF (iShares)',          sector: 'ETF'         },
  { ticker: 'DIA',   name: 'Dow Jones ETF',              sector: 'ETF'         },
  { ticker: 'VIXY',  name: 'VIX ETF (ProShares)',         sector: 'ETF'         },
  { ticker: 'SOXS',  name: 'Semiconductor Bear 3x ETF',  sector: 'ETF'         },
  { ticker: 'TECL',  name: 'Technology Bull 3x ETF',     sector: 'ETF'         },
  { ticker: 'TECS',  name: 'Technology Bear 3x ETF',     sector: 'ETF'         },
  { ticker: 'CURE',  name: 'Healthcare Bull 3x ETF',     sector: 'ETF'         },
  { ticker: 'DPST',  name: 'Banking Bull 3x ETF',        sector: 'ETF'         },
  { ticker: 'NAIL',  name: 'Homebuilding Bull 3x ETF',   sector: 'ETF'         },
  { ticker: 'MSOS',  name: 'Cannabis ETF',               sector: 'ETF'         },
  { ticker: 'BOTZ',  name: 'Robotics & AI ETF',          sector: 'ETF'         },
  { ticker: 'ARKF',  name: 'ARK Fintech Innovation ETF', sector: 'ETF'         },

  // ── Mega-cap tech (additional) ────────────────────────────────────────────
  { ticker: 'GOOG',  name: 'Alphabet Class C',           sector: 'Technology'  },
  { ticker: 'ORCL',  name: 'Oracle',                     sector: 'Technology'  },
  { ticker: 'CRM',   name: 'Salesforce',                 sector: 'Technology'  },
  { ticker: 'ADBE',  name: 'Adobe',                      sector: 'Technology'  },
  { ticker: 'INTC',  name: 'Intel',                      sector: 'Technology'  },
  { ticker: 'QCOM',  name: 'Qualcomm',                   sector: 'Technology'  },
  { ticker: 'AVGO',  name: 'Broadcom',                   sector: 'Technology'  },
  { ticker: 'CSCO',  name: 'Cisco Systems',              sector: 'Technology'  },
  { ticker: 'TXN',   name: 'Texas Instruments',          sector: 'Technology'  },
  { ticker: 'MU',    name: 'Micron Technology',          sector: 'Technology'  },
  { ticker: 'ARM',   name: 'Arm Holdings',               sector: 'Technology'  },
  { ticker: 'MRVL',  name: 'Marvell Technology',         sector: 'Technology'  },
  { ticker: 'ON',    name: 'ON Semiconductor',           sector: 'Technology'  },
  { ticker: 'KLAC',  name: 'KLA Corporation',            sector: 'Technology'  },
  { ticker: 'LRCX',  name: 'Lam Research',               sector: 'Technology'  },
  { ticker: 'AMAT',  name: 'Applied Materials',          sector: 'Technology'  },
  { ticker: 'ASML',  name: 'ASML Holding',               sector: 'Technology'  },
  { ticker: 'TSM',   name: 'Taiwan Semiconductor',       sector: 'Technology'  },
  { ticker: 'NOW',   name: 'ServiceNow',                 sector: 'Technology'  },
  { ticker: 'WDAY',  name: 'Workday',                    sector: 'Technology'  },
  { ticker: 'PANW',  name: 'Palo Alto Networks',         sector: 'Technology'  },
  { ticker: 'ZS',    name: 'Zscaler',                    sector: 'Technology'  },
  { ticker: 'FTNT',  name: 'Fortinet',                   sector: 'Technology'  },
  { ticker: 'OKTA',  name: 'Okta',                       sector: 'Technology'  },
  { ticker: 'TEAM',  name: 'Atlassian',                  sector: 'Technology'  },
  { ticker: 'HUBS',  name: 'HubSpot',                    sector: 'Technology'  },
  { ticker: 'VEEV',  name: 'Veeva Systems',              sector: 'Technology'  },
  { ticker: 'GTLB',  name: 'GitLab',                     sector: 'Technology'  },
  { ticker: 'CFLT',  name: 'Confluent',                  sector: 'Technology'  },
  { ticker: 'MNDY',  name: 'Monday.com',                 sector: 'Technology'  },
  { ticker: 'APP',   name: 'AppLovin',                   sector: 'Technology'  },
  { ticker: 'DUOL',  name: 'Duolingo',                   sector: 'Technology'  },
  { ticker: 'TTD',   name: 'The Trade Desk',             sector: 'Technology'  },
  { ticker: 'ACN',   name: 'Accenture',                  sector: 'Technology'  },
  { ticker: 'IBM',   name: 'IBM',                        sector: 'Technology'  },
  { ticker: 'DELL',  name: 'Dell Technologies',          sector: 'Technology'  },
  { ticker: 'HPQ',   name: 'HP Inc',                     sector: 'Technology'  },
  { ticker: 'HPE',   name: 'Hewlett Packard Enterprise', sector: 'Technology'  },
  { ticker: 'CDNS',  name: 'Cadence Design Systems',     sector: 'Technology'  },
  { ticker: 'SNPS',  name: 'Synopsys',                   sector: 'Technology'  },
  { ticker: 'ANET',  name: 'Arista Networks',              sector: 'Technology'  },
  { ticker: 'MANH',  name: 'Manhattan Associates',       sector: 'Technology'  },
  { ticker: 'EPAM',  name: 'EPAM Systems',               sector: 'Technology'  },
  { ticker: 'CELH',  name: 'Celsius Holdings',           sector: 'Consumer'    },
  { ticker: 'RBRK',  name: 'Rubrik',                     sector: 'Technology'  },
  { ticker: 'CWAN',  name: 'Clearwater Analytics',       sector: 'Technology'  },
  { ticker: 'MGNI',  name: 'Magnite',                    sector: 'Technology'  },
  { ticker: 'MQ',    name: 'Marqeta',                    sector: 'Finance'     },
  { ticker: 'ASAN',  name: 'Asana',                       sector: 'Technology'  },
  { ticker: 'ESTC',  name: 'Elastic',                    sector: 'Technology'  },
  { ticker: 'SWKS',  name: 'Skyworks Solutions',         sector: 'Technology'  },
  { ticker: 'QRVO',  name: 'Qorvo',                      sector: 'Technology'  },
  { ticker: 'MPWR',  name: 'Monolithic Power Systems',   sector: 'Technology'  },
  { ticker: 'ONTO',  name: 'Onto Innovation',            sector: 'Technology'  },
  { ticker: 'FORM',  name: 'FormFactor',                 sector: 'Technology'  },
  { ticker: 'ENTG',  name: 'Entegris',                   sector: 'Technology'  },
  { ticker: 'WOLF',  name: 'Wolfspeed',                  sector: 'Technology'  },
  { ticker: 'AXON',  name: 'Axon Enterprise',            sector: 'Technology'  },
  { ticker: 'KTOS',  name: 'Kratos Defense',             sector: 'Industrial'  },
  { ticker: 'PSTG',  name: 'Pure Storage',               sector: 'Technology'  },
  { ticker: 'STX',   name: 'Seagate Technology',         sector: 'Technology'  },
  { ticker: 'KEYS',  name: 'Keysight Technologies',      sector: 'Technology'  },
  { ticker: 'AEHR',  name: 'Aehr Test Systems',          sector: 'Technology'  },
  { ticker: 'ACMR',  name: 'ACM Research',               sector: 'Technology'  },
  { ticker: 'PATH',  name: 'UiPath',                      sector: 'Technology'  },

  // ── Financials ────────────────────────────────────────────────────────────
  { ticker: 'V',     name: 'Visa',                       sector: 'Finance'     },
  { ticker: 'MA',    name: 'Mastercard',                 sector: 'Finance'     },
  { ticker: 'AXP',   name: 'American Express',           sector: 'Finance'     },
  { ticker: 'COF',   name: 'Capital One',                sector: 'Finance'     },
  { ticker: 'SYF',   name: 'Synchrony Financial',        sector: 'Finance'     },
  { ticker: 'TOST',  name: 'Toast',                       sector: 'Finance'     },
  { ticker: 'MS',    name: 'Morgan Stanley',             sector: 'Finance'     },
  { ticker: 'C',     name: 'Citigroup',                  sector: 'Finance'     },
  { ticker: 'WFC',   name: 'Wells Fargo',                sector: 'Finance'     },
  { ticker: 'SCHW',  name: 'Charles Schwab',             sector: 'Finance'     },
  { ticker: 'BLK',   name: 'BlackRock',                  sector: 'Finance'     },
  { ticker: 'AIG',   name: 'American International Group',sector: 'Finance'    },
  { ticker: 'MET',   name: 'MetLife',                    sector: 'Finance'     },
  { ticker: 'PRU',   name: 'Prudential Financial',       sector: 'Finance'     },
  { ticker: 'AFL',   name: 'Aflac',                      sector: 'Finance'     },
  { ticker: 'ALL',   name: 'Allstate',                   sector: 'Finance'     },
  { ticker: 'PGR',   name: 'Progressive',                sector: 'Finance'     },
  { ticker: 'TRV',   name: 'Travelers Companies',        sector: 'Finance'     },
  { ticker: 'CB',    name: 'Chubb',                      sector: 'Finance'     },
  { ticker: 'MMC',   name: 'Marsh & McLennan',           sector: 'Finance'     },
  { ticker: 'AON',   name: 'Aon',                        sector: 'Finance'     },
  { ticker: 'USB',   name: 'US Bancorp',                 sector: 'Finance'     },
  { ticker: 'PNC',   name: 'PNC Financial',              sector: 'Finance'     },
  { ticker: 'TFC',   name: 'Truist Financial',           sector: 'Finance'     },
  { ticker: 'KEY',   name: 'KeyCorp',                    sector: 'Finance'     },
  { ticker: 'RF',    name: 'Regions Financial',          sector: 'Finance'     },
  { ticker: 'CFG',   name: 'Citizens Financial',         sector: 'Finance'     },
  { ticker: 'HBAN',  name: 'Huntington Bancshares',      sector: 'Finance'     },
  { ticker: 'FITB',  name: 'Fifth Third Bancorp',        sector: 'Finance'     },
  { ticker: 'ALLY',  name: 'Ally Financial',             sector: 'Finance'     },
  { ticker: 'ICE',   name: 'Intercontinental Exchange',  sector: 'Finance'     },
  { ticker: 'CME',   name: 'CME Group',                  sector: 'Finance'     },
  { ticker: 'CBOE',  name: 'Cboe Global Markets',        sector: 'Finance'     },
  { ticker: 'SPGI',  name: 'S&P Global',                 sector: 'Finance'     },
  { ticker: 'MCO',   name: "Moody's",                    sector: 'Finance'     },
  { ticker: 'LC',    name: 'LendingClub',                sector: 'Finance'     },
  { ticker: 'RJF',   name: 'Raymond James Financial',    sector: 'Finance'     },
  { ticker: 'LNC',   name: 'Lincoln National',           sector: 'Finance'     },
  { ticker: 'VOYA',  name: 'Voya Financial',             sector: 'Finance'     },
  { ticker: 'EQH',   name: 'Equitable Holdings',         sector: 'Finance'     },
  { ticker: 'FNF',   name: 'Fidelity National Financial',sector: 'Finance'     },
  { ticker: 'ACGL',  name: 'Arch Capital Group',         sector: 'Finance'     },
  { ticker: 'PYPL',  name: 'PayPal',                     sector: 'Finance'     },
  { ticker: 'NU',    name: 'Nu Holdings',                sector: 'Finance'     },
  { ticker: 'MELI',  name: 'MercadoLibre',               sector: 'Finance'     },
  { ticker: 'OPFI',  name: 'OppFi',                      sector: 'Finance'     },
  { ticker: 'IBKR',  name: 'Interactive Brokers',        sector: 'Finance'     },
  { ticker: 'NDAQ',  name: 'Nasdaq Inc',                 sector: 'Finance'     },
  { ticker: 'HIG',   name: 'Hartford Financial',         sector: 'Finance'     },
  { ticker: 'WEX',   name: 'WEX Inc',                    sector: 'Finance'     },

  // ── Healthcare & Biotech ──────────────────────────────────────────────────
  { ticker: 'UNH',   name: 'UnitedHealth Group',         sector: 'Healthcare'  },
  { ticker: 'JNJ',   name: 'Johnson & Johnson',          sector: 'Healthcare'  },
  { ticker: 'LLY',   name: 'Eli Lilly',                  sector: 'Healthcare'  },
  { ticker: 'ABBV',  name: 'AbbVie',                     sector: 'Healthcare'  },
  { ticker: 'MRK',   name: 'Merck',                      sector: 'Healthcare'  },
  { ticker: 'BMY',   name: 'Bristol-Myers Squibb',       sector: 'Healthcare'  },
  { ticker: 'AMGN',  name: 'Amgen',                      sector: 'Healthcare'  },
  { ticker: 'GILD',  name: 'Gilead Sciences',            sector: 'Healthcare'  },
  { ticker: 'BIIB',  name: 'Biogen',                     sector: 'Healthcare'  },
  { ticker: 'REGN',  name: 'Regeneron Pharmaceuticals',  sector: 'Healthcare'  },
  { ticker: 'MRNA',  name: 'Moderna',                    sector: 'Healthcare'  },
  { ticker: 'VRTX',  name: 'Vertex Pharmaceuticals',     sector: 'Healthcare'  },
  { ticker: 'CVS',   name: 'CVS Health',                 sector: 'Healthcare'  },
  { ticker: 'CI',    name: 'Cigna Group',                sector: 'Healthcare'  },
  { ticker: 'HUM',   name: 'Humana',                     sector: 'Healthcare'  },
  { ticker: 'MDT',   name: 'Medtronic',                  sector: 'Healthcare'  },
  { ticker: 'BSX',   name: 'Boston Scientific',          sector: 'Healthcare'  },
  { ticker: 'EW',    name: 'Edwards Lifesciences',       sector: 'Healthcare'  },
  { ticker: 'ISRG',  name: 'Intuitive Surgical',         sector: 'Healthcare'  },
  { ticker: 'SYK',   name: 'Stryker',                    sector: 'Healthcare'  },
  { ticker: 'ZBH',   name: 'Zimmer Biomet',              sector: 'Healthcare'  },
  { ticker: 'DXCM',  name: 'Dexcom',                     sector: 'Healthcare'  },
  { ticker: 'PODD',  name: 'Insulet',                    sector: 'Healthcare'  },
  { ticker: 'HOLX',  name: 'Hologic',                    sector: 'Healthcare'  },
  { ticker: 'ALGN',  name: 'Align Technology',           sector: 'Healthcare'  },
  { ticker: 'IRTC',  name: 'iRhythm Technologies',       sector: 'Healthcare'  },
  { ticker: 'RMD',   name: 'ResMed',                     sector: 'Healthcare'  },
  { ticker: 'BDX',   name: 'Becton Dickinson',           sector: 'Healthcare'  },
  { ticker: 'BAX',   name: 'Baxter International',       sector: 'Healthcare'  },
  { ticker: 'INCY',  name: 'Incyte',                     sector: 'Healthcare'  },
  { ticker: 'EXEL',  name: 'Exelixis',                   sector: 'Healthcare'  },
  { ticker: 'JAZZ',  name: 'Jazz Pharmaceuticals',       sector: 'Healthcare'  },
  { ticker: 'ALNY',  name: 'Alnylam Pharmaceuticals',    sector: 'Healthcare'  },
  { ticker: 'RARE',  name: 'Ultragenyx Pharmaceutical',  sector: 'Healthcare'  },
  { ticker: 'BMRN',  name: 'BioMarin Pharmaceutical',    sector: 'Healthcare'  },
  { ticker: 'ACAD',  name: 'ACADIA Pharmaceuticals',     sector: 'Healthcare'  },
  { ticker: 'ARWR',  name: 'Arrowhead Pharmaceuticals',  sector: 'Healthcare'  },
  { ticker: 'TMO',   name: 'Thermo Fisher Scientific',   sector: 'Healthcare'  },
  { ticker: 'DHR',   name: 'Danaher',                    sector: 'Healthcare'  },
  { ticker: 'ABT',   name: 'Abbott Laboratories',        sector: 'Healthcare'  },
  { ticker: 'ILMN',  name: 'Illumina',                   sector: 'Healthcare'  },
  { ticker: 'CRSP',  name: 'CRISPR Therapeutics',        sector: 'Healthcare'  },
  { ticker: 'EDIT',  name: 'Editas Medicine',            sector: 'Healthcare'  },
  { ticker: 'AXSM',  name: 'Axsome Therapeutics',        sector: 'Healthcare'  },
  { ticker: 'NUVL',  name: 'Nuvalent',                   sector: 'Healthcare'  },
  { ticker: 'RXRX',  name: 'Recursion Pharmaceuticals',  sector: 'Healthcare'  },
  { ticker: 'VCEL',  name: 'Vericel',                    sector: 'Healthcare'  },
  { ticker: 'PTGX',  name: 'Protagonist Therapeutics',   sector: 'Healthcare'  },
  { ticker: 'GEHC',  name: 'GE HealthCare',              sector: 'Healthcare'  },
  { ticker: 'GKOS',  name: 'Glaukos',                    sector: 'Healthcare'  },

  // ── Consumer / Retail / Restaurants ──────────────────────────────────────
  { ticker: 'WMT',   name: 'Walmart',                    sector: 'Consumer'    },
  { ticker: 'COST',  name: 'Costco',                     sector: 'Consumer'    },
  { ticker: 'TGT',   name: 'Target',                     sector: 'Consumer'    },
  { ticker: 'HD',    name: 'Home Depot',                 sector: 'Consumer'    },
  { ticker: 'LOW',   name: "Lowe's",                     sector: 'Consumer'    },
  { ticker: 'SBUX',  name: 'Starbucks',                  sector: 'Consumer'    },
  { ticker: 'MCD',   name: "McDonald's",                 sector: 'Consumer'    },
  { ticker: 'CMG',   name: 'Chipotle Mexican Grill',     sector: 'Consumer'    },
  { ticker: 'YUM',   name: 'Yum! Brands',               sector: 'Consumer'    },
  { ticker: 'DPZ',   name: "Domino's Pizza",             sector: 'Consumer'    },
  { ticker: 'LULU',  name: 'Lululemon Athletica',        sector: 'Consumer'    },
  { ticker: 'ULTA',  name: 'Ulta Beauty',                sector: 'Consumer'    },
  { ticker: 'EL',    name: 'Estée Lauder',               sector: 'Consumer'    },
  { ticker: 'TJX',   name: 'TJX Companies',              sector: 'Consumer'    },
  { ticker: 'ROST',  name: 'Ross Stores',                sector: 'Consumer'    },
  { ticker: 'BURL',  name: 'Burlington Stores',          sector: 'Consumer'    },
  { ticker: 'ANF',   name: 'Abercrombie & Fitch',        sector: 'Consumer'    },
  { ticker: 'AEO',   name: 'American Eagle Outfitters',  sector: 'Consumer'    },
  { ticker: 'PEP',   name: 'PepsiCo',                    sector: 'Consumer'    },
  { ticker: 'KO',    name: 'Coca-Cola',                  sector: 'Consumer'    },
  { ticker: 'MDLZ',  name: 'Mondelez International',     sector: 'Consumer'    },
  { ticker: 'HSY',   name: 'Hershey',                    sector: 'Consumer'    },
  { ticker: 'GIS',   name: 'General Mills',              sector: 'Consumer'    },
  { ticker: 'TSN',   name: 'Tyson Foods',                sector: 'Consumer'    },
  { ticker: 'ETSY',  name: 'Etsy',                       sector: 'Consumer'    },
  { ticker: 'W',     name: 'Wayfair',                    sector: 'Consumer'    },
  { ticker: 'CHWY',  name: 'Chewy',                      sector: 'Consumer'    },
  { ticker: 'EBAY',  name: 'eBay',                       sector: 'Consumer'    },
  { ticker: 'DASH',  name: 'DoorDash',                   sector: 'Consumer'    },
  { ticker: 'WING',  name: 'Wingstop',                   sector: 'Consumer'    },
  { ticker: 'DRI',   name: 'Darden Restaurants',         sector: 'Consumer'    },
  { ticker: 'TXRH',  name: 'Texas Roadhouse',            sector: 'Consumer'    },
  { ticker: 'SHAK',  name: 'Shake Shack',                sector: 'Consumer'    },
  { ticker: 'BROS',  name: 'Dutch Bros',                 sector: 'Consumer'    },
  { ticker: 'CAVA',  name: 'CAVA Group',                 sector: 'Consumer'    },
  { ticker: 'PTON',  name: 'Peloton',                    sector: 'Consumer'    },
  { ticker: 'BYND',  name: 'Beyond Meat',                sector: 'Consumer'    },
  { ticker: 'DKNG',  name: 'DraftKings',                 sector: 'Consumer'    },
  { ticker: 'PENN',  name: 'PENN Entertainment',         sector: 'Consumer'    },
  { ticker: 'CZR',   name: 'Caesars Entertainment',      sector: 'Consumer'    },
  { ticker: 'STZ',   name: 'Constellation Brands',       sector: 'Consumer'    },
  { ticker: 'MNST',  name: 'Monster Beverage',           sector: 'Consumer'    },
  { ticker: 'TAP',   name: 'Molson Coors',               sector: 'Consumer'    },
  { ticker: 'SE',    name: 'Sea Limited',                sector: 'Technology'  },

  // ── Energy ────────────────────────────────────────────────────────────────
  { ticker: 'COP',   name: 'ConocoPhillips',             sector: 'Energy'      },
  { ticker: 'EOG',   name: 'EOG Resources',              sector: 'Energy'      },
  { ticker: 'SLB',   name: 'SLB (Schlumberger)',          sector: 'Energy'      },
  { ticker: 'HAL',   name: 'Halliburton',                sector: 'Energy'      },
  { ticker: 'MPC',   name: 'Marathon Petroleum',         sector: 'Energy'      },
  { ticker: 'VLO',   name: 'Valero Energy',              sector: 'Energy'      },
  { ticker: 'PSX',   name: 'Phillips 66',                sector: 'Energy'      },
  { ticker: 'OXY',   name: 'Occidental Petroleum',       sector: 'Energy'      },
  { ticker: 'DVN',   name: 'Devon Energy',               sector: 'Energy'      },
  { ticker: 'APA',   name: 'APA Corporation',             sector: 'Energy'      },
  { ticker: 'CHRD',  name: 'Chord Energy',               sector: 'Energy'      },
  { ticker: 'BKR',   name: 'Baker Hughes',               sector: 'Energy'      },
  { ticker: 'FANG',  name: 'Diamondback Energy',         sector: 'Energy'      },
  { ticker: 'CTRA',  name: 'Coterra Energy',             sector: 'Energy'      },
  { ticker: 'SM',    name: 'SM Energy',                  sector: 'Energy'      },
  { ticker: 'MTDR',  name: 'Matador Resources',          sector: 'Energy'      },
  { ticker: 'ENPH',  name: 'Enphase Energy',             sector: 'Energy'      },
  { ticker: 'SEDG',  name: 'SolarEdge Technologies',     sector: 'Energy'      },
  { ticker: 'RUN',   name: 'Sunrun',                     sector: 'Energy'      },
  { ticker: 'PLUG',  name: 'Plug Power',                 sector: 'Energy'      },
  { ticker: 'FCEL',  name: 'FuelCell Energy',            sector: 'Energy'      },
  { ticker: 'CHPT',  name: 'ChargePoint',                sector: 'Energy'      },
  { ticker: 'BLNK',  name: 'Blink Charging',             sector: 'Energy'      },
  { ticker: 'FSLR',  name: 'First Solar',                sector: 'Energy'      },
  { ticker: 'BE',    name: 'Bloom Energy',               sector: 'Energy'      },
  { ticker: 'WMB',   name: 'Williams Companies',         sector: 'Energy'      },
  { ticker: 'KMI',   name: 'Kinder Morgan',              sector: 'Energy'      },
  { ticker: 'OKE',   name: 'ONEOK',                      sector: 'Energy'      },
  { ticker: 'LNG',   name: 'Cheniere Energy',            sector: 'Energy'      },
  { ticker: 'VALE',  name: 'Vale S.A.',                  sector: 'Materials'   },

  // ── Utilities ─────────────────────────────────────────────────────────────
  { ticker: 'NEE',   name: 'NextEra Energy',             sector: 'Utilities'   },
  { ticker: 'DUK',   name: 'Duke Energy',                sector: 'Utilities'   },
  { ticker: 'SO',    name: 'Southern Company',           sector: 'Utilities'   },
  { ticker: 'D',     name: 'Dominion Energy',            sector: 'Utilities'   },
  { ticker: 'EXC',   name: 'Exelon',                     sector: 'Utilities'   },
  { ticker: 'AEP',   name: 'American Electric Power',    sector: 'Utilities'   },
  { ticker: 'PCG',   name: 'PG&E',                       sector: 'Utilities'   },
  { ticker: 'ED',    name: 'Consolidated Edison',        sector: 'Utilities'   },
  { ticker: 'ETR',   name: 'Entergy',                    sector: 'Utilities'   },
  { ticker: 'PEG',   name: 'PSEG',                       sector: 'Utilities'   },

  // ── Industrials ───────────────────────────────────────────────────────────
  { ticker: 'GE',    name: 'GE Aerospace',               sector: 'Industrial'  },
  { ticker: 'HON',   name: 'Honeywell',                  sector: 'Industrial'  },
  { ticker: 'MMM',   name: '3M',                         sector: 'Industrial'  },
  { ticker: 'ETN',   name: 'Eaton',                      sector: 'Industrial'  },
  { ticker: 'EMR',   name: 'Emerson Electric',           sector: 'Industrial'  },
  { ticker: 'ROK',   name: 'Rockwell Automation',        sector: 'Industrial'  },
  { ticker: 'PH',    name: 'Parker Hannifin',            sector: 'Industrial'  },
  { ticker: 'ITW',   name: 'Illinois Tool Works',        sector: 'Industrial'  },
  { ticker: 'DOV',   name: 'Dover',                      sector: 'Industrial'  },
  { ticker: 'IR',    name: 'Ingersoll Rand',             sector: 'Industrial'  },
  { ticker: 'TT',    name: 'Trane Technologies',         sector: 'Industrial'  },
  { ticker: 'JCI',   name: 'Johnson Controls',           sector: 'Industrial'  },
  { ticker: 'AME',   name: 'Ametek',                     sector: 'Industrial'  },
  { ticker: 'ROP',   name: 'Roper Technologies',         sector: 'Industrial'  },
  { ticker: 'CARR',  name: 'Carrier Global',             sector: 'Industrial'  },
  { ticker: 'OTIS',  name: 'Otis Worldwide',             sector: 'Industrial'  },
  { ticker: 'CAT',   name: 'Caterpillar',                sector: 'Industrial'  },
  { ticker: 'DE',    name: 'Deere & Company',            sector: 'Industrial'  },
  { ticker: 'PCAR',  name: 'PACCAR',                     sector: 'Industrial'  },
  { ticker: 'CMI',   name: 'Cummins',                    sector: 'Industrial'  },
  { ticker: 'LMT',   name: 'Lockheed Martin',            sector: 'Industrial'  },
  { ticker: 'NOC',   name: 'Northrop Grumman',           sector: 'Industrial'  },
  { ticker: 'GD',    name: 'General Dynamics',           sector: 'Industrial'  },
  { ticker: 'RTX',   name: 'RTX (Raytheon)',             sector: 'Industrial'  },
  { ticker: 'LDOS',  name: 'Leidos Holdings',            sector: 'Industrial'  },
  { ticker: 'BAH',   name: 'Booz Allen Hamilton',        sector: 'Industrial'  },
  { ticker: 'UPS',   name: 'United Parcel Service',      sector: 'Industrial'  },
  { ticker: 'FDX',   name: 'FedEx',                      sector: 'Industrial'  },
  { ticker: 'CHRW',  name: 'C.H. Robinson',              sector: 'Industrial'  },
  { ticker: 'XPO',   name: 'XPO',                        sector: 'Industrial'  },
  { ticker: 'SAIA',  name: 'Saia',                       sector: 'Industrial'  },
  { ticker: 'ODFL',  name: 'Old Dominion Freight',       sector: 'Industrial'  },
  { ticker: 'JBHT',  name: 'J.B. Hunt Transport',        sector: 'Industrial'  },
  { ticker: 'WM',    name: 'Waste Management',           sector: 'Industrial'  },
  { ticker: 'RSG',   name: 'Republic Services',          sector: 'Industrial'  },

  // ── Materials ─────────────────────────────────────────────────────────────
  { ticker: 'FCX',   name: 'Freeport-McMoRan',           sector: 'Materials'   },
  { ticker: 'NEM',   name: 'Newmont',                    sector: 'Materials'   },
  { ticker: 'GOLD',  name: 'Barrick Gold',               sector: 'Materials'   },
  { ticker: 'AA',    name: 'Alcoa',                      sector: 'Materials'   },
  { ticker: 'MP',    name: 'MP Materials',               sector: 'Materials'   },
  { ticker: 'RS',    name: 'Reliance Steel & Aluminum',   sector: 'Materials'   },
  { ticker: 'CLF',   name: 'Cleveland-Cliffs',           sector: 'Materials'   },
  { ticker: 'STLD',  name: 'Steel Dynamics',             sector: 'Materials'   },
  { ticker: 'NUE',   name: 'Nucor',                      sector: 'Materials'   },
  { ticker: 'CE',    name: 'Celanese',                   sector: 'Materials'   },
  { ticker: 'DOW',   name: 'Dow Inc',                    sector: 'Materials'   },
  { ticker: 'LYB',   name: 'LyondellBasell',             sector: 'Materials'   },
  { ticker: 'PPG',   name: 'PPG Industries',             sector: 'Materials'   },
  { ticker: 'SHW',   name: 'Sherwin-Williams',           sector: 'Materials'   },
  { ticker: 'ALB',   name: 'Albemarle',                  sector: 'Materials'   },

  // ── Real Estate ───────────────────────────────────────────────────────────
  { ticker: 'AMT',   name: 'American Tower',             sector: 'Real Estate' },
  { ticker: 'PLD',   name: 'Prologis',                   sector: 'Real Estate' },
  { ticker: 'EQIX',  name: 'Equinix',                    sector: 'Real Estate' },
  { ticker: 'SPG',   name: 'Simon Property Group',       sector: 'Real Estate' },
  { ticker: 'O',     name: 'Realty Income',              sector: 'Real Estate' },
  { ticker: 'VICI',  name: 'VICI Properties',            sector: 'Real Estate' },
  { ticker: 'WPC',   name: 'W. P. Carey',                sector: 'Real Estate' },
  { ticker: 'CBRE',  name: 'CBRE Group',                 sector: 'Real Estate' },
  { ticker: 'WELL',  name: 'Welltower',                  sector: 'Real Estate' },
  { ticker: 'IRM',   name: 'Iron Mountain',              sector: 'Real Estate' },

  // ── Telecom & Media ───────────────────────────────────────────────────────
  { ticker: 'TMUS',  name: 'T-Mobile US',                sector: 'Telecom'     },
  { ticker: 'VZ',    name: 'Verizon',                    sector: 'Telecom'     },
  { ticker: 'T',     name: 'AT&T',                       sector: 'Telecom'     },
  { ticker: 'CMCSA', name: 'Comcast',                    sector: 'Telecom'     },
  { ticker: 'WBD',   name: 'Warner Bros. Discovery',     sector: 'Telecom'     },
  { ticker: 'SPOT',  name: 'Spotify',                    sector: 'Technology'  },
  { ticker: 'TTWO',  name: 'Take-Two Interactive',       sector: 'Technology'  },
  { ticker: 'EA',    name: 'Electronic Arts',            sector: 'Technology'  },
  { ticker: 'NWSA',  name: 'News Corp',                   sector: 'Consumer'    },
  { ticker: 'FOXA',  name: 'Fox Corp Class A',           sector: 'Consumer'    },
  { ticker: 'NYT',   name: 'New York Times',             sector: 'Consumer'    },
  { ticker: 'IAC',   name: 'IAC',                        sector: 'Technology'  },
  { ticker: 'RDDT',  name: 'Reddit',                     sector: 'Technology'  },
  { ticker: 'PINS',  name: 'Pinterest',                  sector: 'Technology'  },
  { ticker: 'SIRI',  name: 'Sirius XM',                  sector: 'Telecom'     },
  { ticker: 'LYV',   name: 'Live Nation Entertainment',  sector: 'Consumer'    },
  { ticker: 'BILI',  name: 'Bilibili',                   sector: 'Technology'  },
  { ticker: 'TME',   name: 'Tencent Music',              sector: 'Technology'  },

  // ── Automotive (additional) ───────────────────────────────────────────────
  { ticker: 'TM',    name: 'Toyota Motor',               sector: 'Automotive'  },
  { ticker: 'STLA',  name: 'Stellantis',                 sector: 'Automotive'  },
  { ticker: 'LEA',   name: 'Lear',                       sector: 'Automotive'  },
  { ticker: 'BWA',   name: 'BorgWarner',                 sector: 'Automotive'  },
  { ticker: 'APTV',  name: 'Aptiv',                      sector: 'Automotive'  },

  // ── International ADRs ────────────────────────────────────────────────────
  { ticker: 'BABA',  name: 'Alibaba Group',              sector: 'Technology'  },
  { ticker: 'JD',    name: 'JD.com',                     sector: 'Technology'  },
  { ticker: 'PDD',   name: 'PDD Holdings (Temu)',        sector: 'Technology'  },
  { ticker: 'BIDU',  name: 'Baidu',                      sector: 'Technology'  },
  { ticker: 'FUTU',  name: 'Futu Holdings',              sector: 'Finance'     },
  { ticker: 'NIO',   name: 'NIO',                        sector: 'EV'          },
  { ticker: 'XPEV',  name: 'XPeng',                      sector: 'EV'          },
  { ticker: 'LI',    name: 'Li Auto',                    sector: 'EV'          },
  { ticker: 'SAP',   name: 'SAP SE',                     sector: 'Technology'  },
  { ticker: 'RIO',   name: 'Rio Tinto',                  sector: 'Materials'   },
  { ticker: 'BHP',   name: 'BHP Group',                  sector: 'Materials'   },
  { ticker: 'ITUB',  name: 'Itaú Unibanco',              sector: 'Finance'     },
  { ticker: 'BBD',   name: 'Bradesco',                   sector: 'Finance'     },
  { ticker: 'GRAB',  name: 'Grab Holdings',              sector: 'Technology'  },
  { ticker: 'SONY',  name: 'Sony Group',                 sector: 'Technology'  },
  { ticker: 'UBS',   name: 'UBS Group',                  sector: 'Finance'     },
  { ticker: 'TD',    name: 'Toronto-Dominion Bank',      sector: 'Finance'     },
  { ticker: 'RY',    name: 'Royal Bank of Canada',       sector: 'Finance'     },
  { ticker: 'WIT',   name: 'Wipro',                      sector: 'Technology'  },
  { ticker: 'SAN',   name: 'Banco Santander',            sector: 'Finance'     },

  // ── Misc / additional high-premium ────────────────────────────────────────
  { ticker: 'CPRT',  name: 'Copart',                     sector: 'Consumer'    },
  { ticker: 'KMX',   name: 'CarMax',                     sector: 'Consumer'    },
  { ticker: 'CINF',  name: 'Cincinnati Financial',       sector: 'Finance'     },
  { ticker: 'WRB',   name: 'W.R. Berkley',               sector: 'Finance'     },
  { ticker: 'ERIE',  name: 'Erie Indemnity',             sector: 'Finance'     },
  { ticker: 'RLI',   name: 'RLI Corp',                   sector: 'Finance'     },
  { ticker: 'ALGM',  name: 'Allegro MicroSystems',       sector: 'Technology'  },
  { ticker: 'LSCC',  name: 'Lattice Semiconductor',      sector: 'Technology'  },
  { ticker: 'MTSI',  name: 'MACOM Technology',           sector: 'Technology'  },
  { ticker: 'CRUS',  name: 'Cirrus Logic',               sector: 'Technology'  },
];

/** O(1) lookup by ticker */
export const STOCK_META: Record<string, StockMeta> = Object.fromEntries(
  STOCK_LIST.map((s) => [s.ticker, s])
);
